/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacman.gui;

import Pacman.models.LevelHandler;
import Pacman.models.Speelboard;
import java.awt.event.ItemEvent;

/**
 *
 * @author ugur
 */
public class GameFrame extends javax.swing.JFrame {

    private LevelHandler levelhandler = new LevelHandler();
    private Speelboard speelboard = new Speelboard();

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnStart = new javax.swing.JButton();
        BtnRestart = new javax.swing.JButton();
        gamePanel1 = new Pacman.gui.GamePanel();
        Toggle_Pauze = new javax.swing.JToggleButton();
        Btn_levelOne = new javax.swing.JButton();
        Bnt_level2 = new javax.swing.JButton();
        Btn_level3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnStart.setText("Start");
        BtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStartActionPerformed(evt);
            }
        });

        BtnRestart.setText("Herstart");
        BtnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gamePanel1Layout = new javax.swing.GroupLayout(gamePanel1);
        gamePanel1.setLayout(gamePanel1Layout);
        gamePanel1Layout.setHorizontalGroup(
            gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        gamePanel1Layout.setVerticalGroup(
            gamePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        Toggle_Pauze.setText("Pauzeer");
        Toggle_Pauze.setEnabled(false);
        Toggle_Pauze.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Toggle_PauzeItemStateChanged(evt);
            }
        });
        Toggle_Pauze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Toggle_PauzeActionPerformed(evt);
            }
        });

        Btn_levelOne.setText("level 1");
        Btn_levelOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_levelOneActionPerformed(evt);
            }
        });

        Bnt_level2.setText("level 2");
        Bnt_level2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_level2ActionPerformed(evt);
            }
        });

        Btn_level3.setText("level 3");
        Btn_level3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_level3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnStart)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRestart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Toggle_Pauze)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_levelOne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bnt_level2)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_level3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(gamePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gamePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnStart)
                    .addComponent(BtnRestart)
                    .addComponent(Toggle_Pauze)
                    .addComponent(Btn_levelOne)
                    .addComponent(Bnt_level2)
                    .addComponent(Btn_level3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStartActionPerformed
        // TODO add your handling code here:
        gamePanel1.start();
        Toggle_Pauze.setEnabled(true);
    }//GEN-LAST:event_BtnStartActionPerformed

    private void BtnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestartActionPerformed
        // TODO add your handling code here:
        gamePanel1.reset();
    }//GEN-LAST:event_BtnRestartActionPerformed

    private void Toggle_PauzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Toggle_PauzeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Toggle_PauzeActionPerformed

    private void Toggle_PauzeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Toggle_PauzeItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Toggle_Pauze.setText("Hervat");
            gamePanel1.pause();
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            Toggle_Pauze.setText("Pauzeer");
            gamePanel1.hervat();
        }

    }//GEN-LAST:event_Toggle_PauzeItemStateChanged

    private void Btn_levelOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_levelOneActionPerformed
        // TODO add your handling code here:

        System.out.println("level1");
    }//GEN-LAST:event_Btn_levelOneActionPerformed

    private void Bnt_level2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_level2ActionPerformed
        // TODO add your handling code here:
        speelboard.setLevel(levelhandler.level_two);
        speelboard.laden();
    }//GEN-LAST:event_Bnt_level2ActionPerformed

    private void Btn_level3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_level3ActionPerformed
        // TODO add your handling code here:

        System.out.println("level3");
    }//GEN-LAST:event_Btn_level3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bnt_level2;
    private javax.swing.JButton BtnRestart;
    private javax.swing.JButton BtnStart;
    public javax.swing.JButton Btn_level3;
    public javax.swing.JButton Btn_levelOne;
    public javax.swing.JToggleButton Toggle_Pauze;
    private Pacman.gui.GamePanel gamePanel1;
    // End of variables declaration//GEN-END:variables
}
