/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacman.gui;

import Pacman.models.KeyHandler;
import Pacman.models.Pacman;
import java.util.ArrayList;
import Pacman.models.Poppetje;
import Pacman.models.Speelboard;
import java.awt.Graphics;

/**
 *
 * @author Ugur
 */
public class GamePanel extends javax.swing.JPanel {

    private int level;
    private Speelboard speelboard;
    private ArrayList<Poppetje> popjes;
    Pacman pacman;

    public GamePanel() {
        initComponents();
        level = 1;
        initGame();

    }

    public void addkeyPacman() {
        KeyHandler kh = new KeyHandler();

        kh.setPacman(speelboard.pacman);

        kh.setGamePanel(this);
        this.addKeyListener(kh);
    }

    public void initGame() {
        speelboard = new Speelboard(this);
        popjes = new ArrayList<Poppetje>();
        addkeyPacman();

    }

    public void start() {

        try {
            speelboard.timdronkenspook.start();
            speelboard.timslimspook.start();
            speelboard.timpacman.start();
            init();
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void reset() {
        init();
        initGame();
        speelboard.timdronkenspook.restart();
        //speelboard.timslimspook.restart();
        speelboard.timpacman.restart();
    }

    public void pause() {
        try {
            speelboard.timdronkenspook.stop();
            //speelboard.timslimspook.stop();
            speelboard.timpacman.stop();
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void stop() {
        try {
            speelboard.timdronkenspook.stop();
            //speelboard.timslimspook.stop();
            speelboard.timpacman.stop();
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public void hervat() {
        try {
            init();
            speelboard.timdronkenspook.start();
            //speelboard.timslimspook.start();
            speelboard.timpacman.start();
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        speelboard.draw(g);

    }

    private void init() {

        this.requestFocusInWindow();
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(1, 1, 1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 687, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
