/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacman.gui;

import Pacman.models.KeyHandler;
import java.util.ArrayList;
import Pacman.models.Poppetje;
import Pacman.models.Speelboard;
import java.awt.Graphics;

/**
 *
 * @author Ugur
 */
public class GamePanel extends javax.swing.JPanel {

    private int level;
    private Speelboard speelboard;
    private ArrayList<Poppetje> popjes;
    private int punten = 0;

    public GamePanel() {
        initComponents();
        level = 1;

        punten = 0;

        speelboard = new Speelboard(this);
        popjes = new ArrayList<Poppetje>();
        KeyHandler kh = new KeyHandler();

        kh.setPacman(speelboard.pacman);

        kh.setGamePanel(this);

        this.addKeyListener(kh);
    }

    public void start() {
        init();
    }

    public void reset() {

    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        speelboard.draw(g);
    }

    private void init() {

        this.requestFocusInWindow();
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(1, 1, 1));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1145, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 582, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
